### ISSUE TITLE
App.py is not using envvar 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/galaxy-api#100]
Underpass was not working in the production server and  I can see app.py (which is main functionality ) is not using the env var that @eternaltyro  created and hence that causes failure in the production side , Currently, I have added  underpass in the config , which is not a proper way , need refinement

**Comment by eternaltyro** [comment]
@itskshitiz321 There's a fallback that gets values from the config. Let me check.

**Comment by itskshitiz321** [comment]
Here , we are passing database credentials directly reading from config , https://github.com/hotosm/galaxy-api/blob/e45537e46733f1ef3eeb724b92682eb93427208c/src/galaxy/app.py#L142  , should read it from get_db_connection_params() 
 It is referring default connection to PG https://github.com/hotosm/galaxy-api/blob/e45537e46733f1ef3eeb724b92682eb93427208c/src/galaxy/__init__.py#L31 
 Since we are not reading it from this function , Now app.py goes on looking for config block with "UNDERPASS" which is not present in config.txt , we only have PG ( with connection parameter to underpass ) on the production side . So that API connected to underpass will fail since they will not have any db parameters from config
