### ISSUE TITLE
Inconsistent issue type enum values format

### ISSUE THREAD

**Issue by d-rita** [hotosm/galaxy-api#103]
Currently, the issue type enum values used in querying the `user-reports` endpoint have an inconsistent format, i.e. badgeom, badvalue, and incomplete_tags. 
Proposal to have a consistent and readable format, like snake case.

**Comment by robsavoye** [comment]
I'm more into CamelCase. :-) The official version of any enum is what Underpass has defined, as the same enums are also in the database schema. Is that one underbar causing problems, I can always remove it.

**Comment by ramyaragupathy** [comment]
Per discussion today - classes and methods to use camelCase. Enum values will be using snake case.

cc @robsavoye @itskshitiz321

**Comment by itskshitiz321** [comment]
Since its about to making consistent , I just updated new ENUM values without underscore. Will update with underpass accordingly !
