### ISSUE TITLE
Endpoints for data extracts

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#109]
Since Galaxy now has raw OSM data, we can add API calls to support the types of data extracts that export-tool does. Ideally export-tool can use Galaxy instead of Overpass.

**Comment by robsavoye** [comment]
One of the primary uses of data extracts are producing MBTILES to use as basemaps for the OMK/ODK/Kobo mobile tools. Postgres does supporting outputting vector tiles, which the mobile tools support. Other extracts will need to be in OSM XML and GeoJson, so they can be used by the editing tools.

If possible, it'd be great to also output overlay's for OsmAnd, which currently are used by our field teams. This is commonly used to add special information for the mappers, for example, custom boundaries for mapping, or custom POI layers of data not in OSM.

**Comment by ramyaragupathy** [comment]
To be picked for this week's user refinement discussion session

**Comment by ramyaragupathy** [comment]
Since the country based extracts would be dependent on https://github.com/hotosm/underpass/issues/88 and also we have to factor in the computation time for such large areas, we are starting with focus on smaller polygons like TM project boundaries.

cc @itskshitiz321 @robsavoye

**Comment by ramyaragupathy** [comment]
Owing to the current bug in Underpass https://github.com/hotosm/underpass/issues/96 - we will be relying on [Insights data source](https://github.com/hotosm/insights) for raw data extracts.

**Comment by ramyaragupathy** [comment]
Related [Extracting raw data based on polygon input](https://github.com/hotosm/galaxy-api/issues/116)
