### ISSUE TITLE
Endpoint  Returning result in negative numbers 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/galaxy-api#115]
```

{
    "fromTimestamp": "2021-12-28T07:00:00.330",
    "toTimestamp": "2021-12-28T15:22:21.330",
    "projectIds": [],
    "hashtags": [
        "maproulette"
    ]
}
```
With the help of @d-rita  While passing this parameter to detailed report 
I can see endpoint is returning this type of result for mapped tasks, validated tasks with negative number , Is it expected output ? Why we are even accepting negative numbers ? It should be positive integer instead , Is there any case for negative scenario ?
```
    {
      "userId": ###,
      "username": "###",
      "totalBuildings": 6,
      "mappedTasks": -1,
      "validatedTasks": -1,
      "editors": "iD 2.20.2,"
    }
```
cc: @ramyaragupathy  @omranlm

**Comment by ramyaragupathy** [comment]
Ideally this should be zero or a positive integer. Looks like the task stats update is failing within Tasking Manager. I will check the results in TM backend and post update here
