### ISSUE TITLE
Mapathon reports should be case insensitive 

### ISSUE THREAD

**Issue by omranlm** [hotosm/galaxy-api#125]
@itskshitiz321 
in Mapathon summary and details API the query is case sensitive, to be consistent we just need to update the "like" condision to "ilike" one in the query sent to insights:

The change should be [here ](https://github.com/hotosm/galaxy-api/blob/cd4dae1b3dd76a27f5be77ed3e466ccaf3558d23/src/galaxy/query_builder/builder.py#L32) I think with ~~* operation
Below example of different stats for #missingmaps and #MissingMaps hashtags 

![image](https://user-images.githubusercontent.com/39491329/149980392-603146f2-d2a0-4394-b5f2-1ae3dd5100d2.png)

![image](https://user-images.githubusercontent.com/39491329/149980473-0c47fde5-ab1d-45bf-b57c-f7e19d2b4880.png)

**Comment by itskshitiz321** [comment]
- Related to #122

**Comment by itskshitiz321** [comment]
Picking Up this issue as a quick fix , Since it is directly affecting our Mapathon Report Published in frontend ! 
cc: @ramyaragupathy  @omranlm

**Comment by itskshitiz321** [comment]
We will need to check duplicate values in the hashtags input as well , Because after implementing this fix MissingMaps and missingmaps will be treated same and hence when user inputs both they should be considered as duplicate values otherwise stats will be duplicated , doubled !
