### ISSUE TITLE
Evaluate the option of replacing Overpass data source for Export Tool

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-api#164]
Our long term goal is to replace Overpass as a data source for Export Tool. Now that we have the raw data extraction working through the Galaxy API, we should evaluate the feasibility of code changes within Export Tool.

**Comment by itskshitiz321** [comment]
Based on @robsavoye suggestion ,Added ogr export functionality in Galaxy API , now galaxy API can work using ogr2ogr for file conversion , I have made it optional for now ,and added kml support for testing ogr 
cc : @ramyaragupathy 
- https://github.com/hotosm/galaxy-api/commit/b9a5f8d06800bc145aab25714a3c29d4f073f57e
