### ISSUE TITLE
Generate Tasking Manager validator statistics

### ISSUE THREAD

**Issue by jorgemrtnz** [hotosm/galaxy-api#185]
The api needs to connect to Tasking Manager to generate the statistics of all validators in a given year. The following tasks are needed

- [x] Create SQL query to collect the user statistics per project, per year.
- [x] Structure data in the format that fulfills the given requirements.
- [x] Include additional project information: country, tasks_mapped, tasks_validated, total_tasks and organization.
- [ ] Write api endpoint that generates previous query and outputs the csv file.
- [ ] Include country, year and organization filters within endpoint.
- [ ] Include tests to validate the api request to sql query transformation.

**Comment by itskshitiz321** [comment]
- Fixed with https://github.com/hotosm/galaxy-api/pull/201
