### ISSUE TITLE
Update documentation - Community Standard checklist

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/galaxy-api#188]
Adding an issue to Review  and Update documentation included in the checklist under Community Standards:

https://github.com/hotosm/galaxy-api/community

@ramyaragupathy  added issue here and can start working on this in this sprint.

**Comment by ramyaragupathy** [comment]
Sounds good @petya-kangalova

**Comment by petya-kangalova** [comment]
@ramyaragupathy  I wasn't able to edit the description for some reason. Maybe we can check jointly if it is permission related. The rest I submitted as PRs:

https://github.com/hotosm/galaxy-api/pulls/petya-kangalova

For the contributor guidelines, I wanted to briefly chat to you before adding so that we make the guidelines more specific. We can speak tomorrow :)
