### ISSUE TITLE
Have multiple test and Research on index creation, Performance enhancement On Planet data

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#197]
Considering within this sprint planet data will be available on RDS, Now multiple tests needs to be done with the data we have , plan is to begin with two important tests in this sprint : 

- Multiple tests on index creations 
- Multiple performance enhancement techniques implementation 

This could raise a series of issues once tests are done, for eg : Data partitioning could be the next task to do. This test and research should give us clear vision where can we go from this situation with planet import and required next actions

**Comment by itskshitiz321** [comment]
![data_structure_ (1)](https://user-images.githubusercontent.com/36752999/166421746-0bcb342e-6285-4064-a0fa-e0d6c6194111.png)
![api_workflow (1)](https://user-images.githubusercontent.com/36752999/166421751-ba3f1787-6a80-43d6-b318-ed2e47befc27.png)
![general_workflow (1)](https://user-images.githubusercontent.com/36752999/166421754-ccd23856-dd9e-46f1-bcb7-6c633624f068.png)
