### ISSUE TITLE
Add Geojson Option in Export Tool and Connect it to Galaxy API 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#203]
Plan is to create Geojson Output format functionality in Export tool . We will follow step by step approach on integration of galaxy api to export tool. Frist step will be adding Geojson option in export tool itself and provide data through galaxy with that output format for now !

**Comment by ramyaragupathy** [comment]
@itskshitiz321 - does it involve tasks both on the Export Tool frontend and backend?

**Comment by itskshitiz321** [comment]
That's Right ! @ramyaragupathy
