### ISSUE TITLE
 Standardise API Request Body with it's acceptance Criteria : Rawdata

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#209]
Plan is to enhance API request body with standard format in user readable way + make it more clear for users and other developers . Since API supports requirement for both export tool and standard user , we need to derive a better and common approach for the API request body

**Comment by itskshitiz321** [comment]
From multiple discussion we arrived to conclusion to go with following example request body for rawdata endpoint , Validation and acceptance criteria will be applied as required initially and updated on this same thread as comment 
```
{
  "outputType": "GeoJSON",
  "fileName": "string",
  "geometry": {
    "coordinates": [
      [
        [
          "string"
        ],
        [
          "string"
        ]
      ]
    ],
    "type": "string"
  },
  "filters" : {
    "tags": { # no of rows returned 
      "point" : {"amenity":["shop"]},
      "line" : {},
      "polygon" : {"key":["value"]},
      "all_geometry" : {"building":['yes']}
      },
    "attributes": { # no of columns / name 
      "point": [], column 
      "line" : [],
      "polygon" : [],
      "all_geometry" : [],
      }
     },
  "geometryType": [
    "point","line","polygon"
  ]
}
```
