### ISSUE TITLE
 Setup Versioning in API and release first version ! 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/galaxy-api#231]
Plan is to setup versioning on api so that endpoint for first version will look like v1/endpoints/ , and as soon we work on new features we will increase the version ! Fast API will support the API versioning 
cc: @ramyaragupathy  @eternaltyro @dakotabenjamin

**Comment by ramyaragupathy** [comment]
Not an immediate priority for the export tool deployment, however we can pick this for the next quarter API planning

**Comment by kshitijrajsharma** [comment]
Picking up this , for the versioning of API
