### ISSUE TITLE
SQL endpoint for TM project quality

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#27]
Add a file & class for validation queries. There will be several of these for different types of validation analysis, this task is focused on just a single endpoint. This class should take a _hashtag_ and _polygon_ and query the **validation** table in **osmstats**. An additional parameter will also be needed to filter data by time interval. A time interval is an optional starting and ending time for the query. There are currently two values in the validation table, badvalue and badgeom. There are other optional values for this database column that will also need to be supported. These are incomplete, and complete, which are used with the optional tag completeness validation, which isn't enable by default at runtime.

The output of this query should be the location and other relevant tags to aid the human validator. Layered on top of this query is also support to export the data returned from the query as either CSV or GeoJson.

**Comment by itskshitiz321** [comment]
This issue is large and  fulfilled by multiple PR , One of them is

-   #75  which covers most of the use case scenario for this ! Currently we have solved this with multiple small issues can be seen in following thread 
-  #57,
We can always come back here , whenever needed
