### ISSUE TITLE
Create a base class for output

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#28]
Multiple endpoints in the API need to support exporting data in a form it can be used in other programs. The two formats to support are CSV and GeoJson. While postgres can output a query in these formats, there are also numerous python modules that can be used for more control over the output. Since the SQL queries will be generating the input to this class, there will need to be a flexible and portable data flow between them.

**Comment by itskshitiz321** [comment]
Will be using **Pandas** for this ! 
Pandas is one of the most widely used python libraries in data science. It provides high-performance, easy to use structures and data analysis tools. Unlike NumPy library which provides objects for multi-dimensional arrays, Pandas provides an in-memory 2d table object called Dataframe. It is like a spreadsheet with column names and row labels.
Hence, with 2d tables, pandas is capable of providing many additional functionalities like creating pivot tables, computing columns based on other columns and plotting graphs, which will be useful for the future as well .

**Comment by itskshitiz321** [comment]
Now we can pass default SQL Query output in our Output class . It also supports dict , list , json and even query string , Any endpoints can call output class with the result they have and can get data in csv , json , dict , list . Tested this with mapathon endpoint. 
Here is a example of usage of output class 
```csv_out=Output(mapathon_contributor_result).to_CSV(filepath) ```
