### ISSUE TITLE
Rename osmstats to Galaxy

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#44]
For better branding and less confusion with the older osm-stats database used by Leaderboard, the where ever osm-stats or osmstats, etc... should be renamed to 'galaxy; This is the Galaxy API, and does more than just osm-stats. This includes renaming the github repository.

**Comment by itskshitiz321** [comment]
Renaming Github Repo will require Done by Repo owner , However, successfully renamed osm_stats to galaxy and package name to OSM_Package !  
@ramyaragupathy @dakotabenjamin

**Comment by itskshitiz321** [comment]
Also, this task will be required to rename it in JIRA and wherever it is used as osm_stats_API

**Comment by ramyaragupathy** [comment]
@itskshitiz321 @robsavoye - let's keep thisone  along with the implementation details for data quality reports for the user refinement session tomorrow. This will involve changes to the existing component overview we have for Galaxy and will feed into our upcoming summit presentation.

cc @JorgeMartinezG @omranlm @d-rita
