### ISSUE TITLE
Filter data quality reports by Tasking Manager Project ID

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/galaxy-api#47]
An API endpoint that filters out data quality issues for a specific Tasking Manager Project ID

**Data Source:**
Underpass

**Sample request body:**
```
{
  “project_ids”:[],
  “issue_type”: ["bad_geometry", "bad_value", "incomplete_tags", "all"]
}

```

**Acceptance Criteria:**
* User feeds in a Tasking manager Project ID
   * Required input
   * Integer array field
   * Any Non-integer value in the array should throw an error - 400 Bad Request
   * Non-empty array should throw an error -  400 Bad Request
* User can select the data quality issue from a list of options
     * Required input value
     * String array
            - bad_geometry 
            - bad_value 
            - incomplete_tags
            - all

   * Any field other than the options provided should throw an error -  400 Bad Request
   * Non-empty array should throw an error -  400 Bad Request
**Output file format:**
GeoJSON 
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
“Osm_id”: int
“Changeset_id”: int
“Changeset_timestamp”: timestamp
“Issue_type”:string
},
      "geometry": {
        "type": "Point",
        "coordinates": [
          97.734375,
          58.26328705248601
        ]
      }
    }
  ]
}
```
CSV: OSM ID|Changeset ID|latitude|longitude|timestamp|Issue type

**Comment by ramyaragupathy** [comment]
cc @itskshitiz321 @robsavoye @omranlm @JorgeMartinezG

**Comment by itskshitiz321** [comment]
Related to #26

**Comment by itskshitiz321** [comment]
**Divided this task :**
- [ ] Acceptance Criteria Development
- [ ] Query Development
- [ ] Logic Development inside class
- [ ] API Binding
