### ISSUE TITLE
Add AGPLv3 to the code

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#50]
Currently there is no software license for the galaxy-api. After many months of discussion, An example of this in in the HOT qa-tiles repository: https://github.com/hotosm/hot-qa-tiles. This includes the copyright block at the top of all files, and a copy of the agpl license in the top level directory.

**Comment by itskshitiz321** [comment]
Added license 
https://github.com/itskshitiz321/osm-stats-api/commit/e0051e74af6bdc8702f4f322bc96a94b043699d2

**Comment by itskshitiz321** [comment]
![image](https://user-images.githubusercontent.com/36752999/141231075-c918ec92-cef6-423c-acd0-a4a6bceee528.png)
![image](https://user-images.githubusercontent.com/36752999/141231126-32f51162-d06f-4244-9614-ca943e6572a0.png)

**Comment by itskshitiz321** [comment]
![image](https://user-images.githubusercontent.com/36752999/141231244-22665fbe-0f86-47d6-bed7-c18c0bbe3ef9.png)
