### ISSUE TITLE
Import Leaderboard database

### ISSUE THREAD

**Issue by robsavoye** [hotosm/galaxy-api#66]
Underpass contains a python utility, *util/stats2galaxy.py*, which reads the the existing Leaderboard database and converts it to the database schema used by Galaxy. There is a recent dump of the Leaderboard database in the /data subdirectory on the new EC2 instance. The file is mm-osm-stats-20211110.dump. This file initially needs to be imported into postgre. The script reads from that database and writes it to the Galaxy database. This will populate the Galaxy statistics database with many years of historical statistics.

When Underpass runs, it'll update any existing records in the database, but this will help bootstrap Galaxy with the historical statistics.

**Comment by itskshitiz321** [comment]
Outdated !
