### ISSUE TITLE
Remove config object from multiple paths and move config to src

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/galaxy-api#67]
```API/osm_users.py
API/__init__.py
src/galaxy/__init__.py
src/galaxy/app.py
```
these are the files that created a config object on each, The idea is to initialize config in app.py only and use it from outside if needed for that we need to move the config file to src to avoid folder pointing issue  
cc : @JorgeMartinezG

**Comment by itskshitiz321** [comment]
```from src.galaxy import config ```
Now this will work in required places currently applied to auth

**Comment by ramyaragupathy** [comment]
@eternaltyro - looks like the config file should be picked from `src`, your current work looks at  config file in`data` path.

cc @itskshitiz321 @JorgeMartinezG
