### ISSUE TITLE
Enhancement to the mapathon end points 

### ISSUE THREAD

**Issue by omranlm** [hotosm/galaxy-api#76]
One enhancement to the API is to cover hashtags when they don't have semicolon (for hashtags) or space (for comment) which happens when the hashtag of interest is at the end of the hashtags or comment of changeset
sample of the enhanced query 
![image](https://user-images.githubusercontent.com/39491329/143472521-43974965-d55b-492a-89d2-a8f6edde4d64.png)

> 

> Sample

      WITH T1 AS( SELECT user_id, id as changeset_id, user_name as username
      FROM osm_changeset
      WHERE "created_at" between '2021-09-24T07:00:00'::timestamp AND '2021-09-24T16:00:00'::timestamp AND 
    	  (
		      ("tags" -> 'hashtags') ~~ '%hotosm-project-11495;%' OR ("tags" -> 'comment') ~~ '%hotosm-project-11495 %' or ("tags" -> 'hashtags') ~~ '%hotosm-project-11495' OR ("tags" -> 'comment') ~~ '%hotosm-project-11495' or
		      ("tags" -> 'hashtags') ~~ '%hotosm-project-11494;%' OR ("tags" -> 'comment') ~~ '%hotosm-project-11494 %' or ("tags" -> 'hashtags') ~~ '%hotosm-project-11494' OR ("tags" -> 'comment') ~~ '%hotosm-project-11494' or
		  	  ("tags" -> 'hashtags') ~~ '%OSM_Inspector;%'        OR ("tags" -> 'comment') ~~ '%OSM_Inspector %'        or ("tags" -> 'hashtags') ~~ '%OSM_Inspector'        OR ("tags" -> 'comment') ~~ '%OSM_Inspector' 
    	  )
      )
      SELECT (each(tags)).key AS feature, 
    	  action, 
    	  count(distinct id) AS count 
    	  FROM osm_element_history AS t2, t1
      WHERE t1.changeset_id = t2.changeset
    GROUP BY feature, action ORDER BY count desc

@JorgeMartinezG @itskshitiz321

**Comment by itskshitiz321** [comment]
This is also related to testing, Here  #70
